services:
  electricity:
    image: gjmlk/electricity-supply:2.0.0
    ports:
      - name: electricity
        target: 5100
        published: 8100
    networks:
      - frontend
    depends_on:
      - redis
    container_name: electricity-supply-service
    hostname: electricity.docker
  redis:
    image: redis/redis-stack:latest
    container_name: redis-service
    hostname: redis.docker
    ports:
      - name: redis
        target: 6379
        published: 16379
      - name: redis-commander
        target: 8001
        published: 18001
    networks:
      - frontend
    environment:
      REDIS_ARGS: --save 120 1
    volumes:
      - redis_data:/data
networks:
  frontend:
volumes:
  redis_data: