services:
  electricity:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_PORT=5100
    ports:
      - "8100:5100"
    networks:
      - frontend
    depends_on:
      - redis
    container_name: electricity
    hostname: electricity.docker
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    hostname: redis.docker
    ports:
      - "16379:6379"
      - '18001:8001'
    networks:
      - frontend
    environment:
      REDIS_ARGS: --save 120 1
    volumes:
      - redis_data:/data
networks:
  frontend:
volumes:
  redis_data: