version: '3.9'
services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '16379:6379'
      - '18001:8001'
    volumes:
      - ${HOME}/.redisdb:/data
    environment:
      REDIS_ARGS: --save 60 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure