services:
  energy-api:
    build:
      context: homeMGBackCountry
    ports:
      - "8100:5000"
    networks:
      - frontend
#    depends_on:
#      - redis-db
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
    hostname: energy.docker
#  redis-db:
#    image: redis/redis-stack
#    hostname: redis.docker
#    ports:
#      - "16379:6379"
#    networks:
#      - frontend
#    volumes:
#      - redis_data:/data
networks:
  frontend:
volumes:
  redis_data:
