services:
  home-api:
    build:
      context: homeMGBackCountry
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - FLASK_PORT=5100
    ports:
      - 8100:5100
    networks:
      - frontend
    depends_on:
      - redis-db
    container_name: home-api
    hostname: home.app.docker
  redis-db:
    image: redis/redis-stack
    container_name: redis-db
    hostname: redis.docker
    ports:
      - "16379:6379"
      - '18001:8001'
    networks:
      - frontend
    environment:
      REDIS_ARGS: --save 120 1
    volumes:
      - redis_data:/data
networks:
  frontend:
volumes:
  redis_data: