apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.redisPort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}