apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-app-deploy
  namespace: redis-db
  labels:
    app: home-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-app
  template:
    metadata:
      labels:
        app: home-app
    spec:
      containers:
        - name: home-app
          image: gjmlk/home-app:0.1.0
          ports:
            - containerPort: 5100
---
apiVersion: v1
kind: Service
metadata:
  name: home-app-service
  namespace: redis-db
  labels:
    app: home-app
spec:
  type: LoadBalancer
  ports:
    - port: 5100
      targetPort: 5100
      nodePort: 30001
      protocol: TCP
  selector:
    app: home-app