# Redis Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: redis-db
---
# Redis PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: redis-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis" # If you encounter a permission error, create this directory on your worker node.
---
# Redis PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-db
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30079
  selector:
    app: redis
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: redis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack # You can use any image you prefer
          ports:
            - containerPort: 6379
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: redis-storage
              mountPath: /redis/redis-stack
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc