apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
      nodePort: {{ .Values.appNodePort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}