apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pv
  namespace:  {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath }}